### ISSUE TITLE
Analysis: FASTQ, FASTQ.GZ and BAM formats not recognized

### ISSUE THREAD

**Issue by emar2204** [gretep/oncoreport#13]
All these extensions give rise to an error like this:
<html>
<body>
<div class="MuiDialogTitle-root" style="box-sizing: inherit; flex: 0 0 auto; margin: 0px; padding: 16px 24px;"><h2 class="MuiTypography-root MuiTypography-h6" style="box-sizing: inherit; margin: 0px; font-size: 1.25rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.6; letter-spacing: 0.0075em;">Logs of BL35FASTQ</h2></div><div class="MuiDialogContent-root" style="box-sizing: inherit; flex: 1 1 auto; padding: 8px 24px; overflow-y: auto;"><pre style="box-sizing: inherit;">Error: App\Exceptions\ProcessingJobException: Job input format is not valid in /oncoreport/ws/app/Jobs/Request.php:66
Stack trace:
#0 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\Request-&gt;handle()
#1 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#2 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#3 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#4 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#5 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container-&gt;call()
#6 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher-&gt;Illuminate\Bus\{closure}()
#7 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#8 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline-&gt;then()
#9 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher-&gt;dispatchNow()
#10 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler-&gt;Illuminate\Queue\{closure}()
#11 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}()
#12 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline-&gt;then()
#13 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler-&gt;dispatchThroughMiddleware()
#14 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler-&gt;call()
#15 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job-&gt;fire()
#16 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker-&gt;process()
#17 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker-&gt;runJob()
#18 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker-&gt;daemon()
#19 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand-&gt;runWorker()
#20 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand-&gt;handle()
#21 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#23 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#24 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#25 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container-&gt;call()
#26 /oncoreport/ws/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command-&gt;execute()
#27 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command-&gt;run()
#28 /oncoreport/ws/vendor/symfony/console/Application.php(1015): Illuminate\Console\Command-&gt;run()
#29 /oncoreport/ws/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application-&gt;doRunCommand()
#30 /oncoreport/ws/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application-&gt;doRun()
#31 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application-&gt;run()
#32 /oncoreport/ws/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application-&gt;run()
#33 /oncoreport/ws/artisan(37): Illuminate\Foundation\Console\Kernel-&gt;handle()
#34 {main}</pre></div></div></div></div>
</body>
</html>

![FASTQ_BAM](https://user-images.githubusercontent.com/73219438/152186934-09da0063-98fa-4c5c-81c3-9b3b69659a8c.PNG)

**Comment by alaimos** [comment]
This issue is connected to internet connection stability and upload chunks size that corrupt files.
It is not related to Oncoreport itself.
