### ISSUE TITLE
Required field not working

### ISSUE THREAD

**Issue by emar2204** [gretep/oncoreport#21]
When starting a new analysis "Sample Code" field should be mandatory, but it is possible to proceed with the setup phase.

![no_sample_code_required](https://user-images.githubusercontent.com/73219438/161038029-3b180949-2543-44fa-a90e-db35fc9abecb.PNG)

**Comment by alaimos** [comment]
This is not bug. You can set all the parameters when you want. The steps are there only to group related parameters, but you are not required to add them from the beginning. Indeed, validation is only performed right before submission or after altering a field with an invalid value.
