### ISSUE TITLE
Analisi fallisce con container locale.

### ISSUE THREAD

**Issue by Rickrk4** [gretep/oncoreport#23]
L'analisi fallisce con l'installazione locale del container con tutti i tipi di file in input. Di seguito i log dell'errore.
[BL19-53_S1.bam.log](https://github.com/gretep/oncoreport/files/8510894/BL19-53_S1.bam.log)
[BL19-53_S1.fastq.log](https://github.com/gretep/oncoreport/files/8510895/BL19-53_S1.fastq.log)
[BL19-54_S2.log](https://github.com/gretep/oncoreport/files/8510896/BL19-54_S2.log)
.

**Comment by alaimos** [comment]
Non è un bug, gli indici non sono installati correttamente.
